force-app/main/default/objects/Beer__c/Beer__c.object-meta.xml
<CustomObject>
    <label>Beer</label>
    <nameField>
        <label>Beer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Beer__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <externalId>true</externalId>
    <label>Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Beer__c/fields/Tagline__c.field-meta.xml
<CustomField>
    <fullName>Tagline__c</fullName>
    <label>Tagline</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExternalBeersTest.cls
@isTest
private class ExternalBeersTest {
    
    @testSetup
    static void setup() {
        //Create a Beer
		Beer__c aBeer = new Beer__c();
		aBeer.Id__c = '1';
		aBeer.Name__c = 'Name Mock01';
		aBeer.Tagline__c = 'Tag Mock01';
		aBeer.Description__c = 'Description Mock01';        
        Test.startTest();
        insert aBeer;
    }
    
    @isTest static  void testgetExternalBeersCall() {
		//OK
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('GetBeerResource');
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        mock.setStatusCode(200);  
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        Integer result = ExternalBeers.getExternalBeersCall();
        Test.stopTest();
        System.assertNotEquals(null,result, 'The callout returned a null response.');
        System.assertEquals(200,result, 'The status code is not 200.');

    }   
    
    @isTest static  void testgetExternalBeersCallFailure400() {
		//bad request
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('GetBeerResource');
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        mock.setStatusCode(400);
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        Integer result = ExternalBeers.getExternalBeersCall();
        Test.stopTest();
        System.assertNotEquals(null,result, 'The callout returned a null response.');
        System.assertEquals(200,result, 'The status code is not 200.');

    }  

    @isTest static  void testgetExternalBeersCallFailure404() {
		//object not found
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('GetBeerResource');
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        mock.setStatusCode(404);
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        Integer result = ExternalBeers.getExternalBeersCall();
        Test.stopTest();
        System.assertNotEquals(null,result, 'The callout returned a null response.');
        System.assertEquals(200,result, 'The status code is not 200.');

    }  

    @isTest static  void testgetExternalBeersCallFailure503() {
		//service unavailable
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('GetBeerResource');
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        mock.setStatusCode(503);
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        Integer result = ExternalBeers.getExternalBeersCall();
        Test.stopTest();
        System.assertNotEquals(null,result, 'The callout returned a null response.');
        System.assertEquals(200,result, 'The status code is not 200.');

    }  

    @isTest static  void testgetExternalBeersCallFailure596() {
		//service not found
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('GetBeerResource');
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        mock.setStatusCode(596);
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        Integer result = ExternalBeers.getExternalBeersCall();
        Test.stopTest();
        System.assertNotEquals(null,result, 'The callout returned a null response.');
        System.assertEquals(200,result, 'The status code is not 200.');

    }  
    
}